name: build & deploy

on:
  push:
    branches: ['main']
    tags:
      - '*'

env:
  project: aliyun-rest
  REGISTRY: registry.cn-shanghai.aliyuncs.com
  IMAGE_NAME: dysh/mirror

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to aliyun
        uses: aliyun/acr-login@v1
        with:
          login-server: '${{ env.REGISTRY }}'
          username: 'docloud'
          password: '${{ secrets.REGISTRY_PASSWORD }}'

      - name: build & push to aliyun
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.project }} .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.project }}

      - name: Dispatch deploy event
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: deploy
          repository: joy2fun/ansible
          token: ${{ secrets.PAT }}
          client-payload: |-
            {
              "host": "w1",
              "project": "${{ env.project }}",
              "type": "laravel"
            }
